site_name: epwg.de tools
site_url: https://epwg.de
site_author: René Rüthlein

theme:
    name: risonia
    manifest: manifest.json
    serviceworker: service-worker.js
    custom_dir: files/
    logo: img/logo.svg
    extlink: true
    extblank: true

nav:
    - 'index.md'
    - Informatik:
      - 'dice.md'
      - 'ip.md'
      - 'ts.md'
    - Astronomie:
      - 'sun.md'
    - Elektrotechnik:
      - 'resist.md'
      - 'wire.md'

plugins:
  - search:
      lang: de
  - i18n:
      default_language: de
      default_language_only: false
      docs_structure: suffix
      languages:
        default:
          name: Deutsch
          build: true
          site_name: "epwg.de Tools"
        fr:
          name: Français
          build: true
          site_name: "l'outils epwg.de"
        en:
          name: English
          build: true
          site_name: "epwg.de tools"
      nav_translations:
        fr:
          Informatik: Informatique
          Astronomie: Astronomie
          Elektrotechnik: Électrotechnique
        en:
          Informatik: Informatics
          Astronomie: Astronomy
          Elektrotechnik: Electrical engineering
  - color-theme:
      theme_color: '#ff9933' #'#FF9933'
      secondary_color: 'complementary'
  - w3css-classes: {}
  - encryptcontent:
      title_prefix: ''
      summary: 'Verschlüsselte Testseite.'
      placeholder: '12345'
      password_button_text: 'ENTER'
      decryption_failure_message: 'Falsches Passwort, bitte "12345" eingeben.'
      encryption_info_message: 'Bitte "12345" eingeben.'
      input_class: 'w3-input'
      button_class: 'w3-button w3-theme-l1 w3-hover-theme'
      hljs: False
      arithmatex: False
      mermaid2: False
      remember_password: true
      session_storage: true
      encrypted_something:
        myNav: [div, id]
        myToc: [div, id]
        myTocButton: [div, id]
      search_index: 'dynamically' #dynamically
      password_button: True
      selfhost: true
      selfhost_download: false
      reload_scripts:
        - '#theme'
      translations:
        en:
          title_prefix: ''
          summary: 'Encrypted Test Page.'
          placeholder: '12345'
          password_button_text: 'ENTER'
          decryption_failure_message: 'Wrong password, please enter "12345".'
          encryption_info_message: 'Please enter "12345".'

markdown_extensions:
    - attr_list
    - pymdownx.escapeall:
        hardbreak: true