site_name: epwg.de tools
site_url: https://epwg.de
site_author: René Rüthlein

theme:
    name: w3csstheme
    manifest: manifest.json
    serviceworker: service-worker.js
    custom_dir: files/
    logo: img/logo.svg

nav:
    - 'index.md'
    - Informatik:
      - 'dice.md'
      - 'ip.md'
      - 'ts.md'
    - Astronomie:
      - 'sun.md'
    - Elektrotechnik:
      - 'resist.md'
      - 'wire.md'

plugins:
  - i18n:
      default_language: de
      default_language_only: false
      docs_structure: suffix
      languages:
        default:
          name: Deutsch
          build: true
          site_name: "epwg.de Tools"
        fr:
          name: Français
          build: true
          site_name: "l'outils epwg.de"
        en:
          name: English
          build: true
          site_name: "epwg.de tools"
      nav_translations:
        fr:
          Informatik: Informatique
          Astronomie: Astronomie
          Elektrotechnik: Électrotechnique
        en:
          Informatik: Informatics
          Astronomie: Astronomy
          Elektrotechnik: Electrical engineering
  - color-theme:
      theme_color: '#f65708' #'#FF9933'
  - w3css-classes: {}
  - search:
      lang: de

markdown_extensions:
    - attr_list