site_name: epwg.de tools
site_url: https://epwg.de
site_author: René Rüthlein

theme:
    name: risonia
    manifest: manifest.json
    serviceworker: service-worker.js
    custom_dir: files/
    logo: img/logo.svg
    extlink: true
    extblank: true
    toc_sidebar: false

nav:
    - 'index.md'
    - Informatik:
      - 'dice.md'
      - 'ip.md'
      - 'ts.md'
      - 'binary.md'
    - Astronomie:
      - 'sun.md'
    - Elektrotechnik:
      - 'resist.md'
      - 'wire.md'

plugins:
  #- search:
  #    lang: de

  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - build: true
          default: true
          locale: de
          name: Deutsch
          site_name: epwg.de Tools
      #  - build: true
      #    default: false
      #    locale: fr
      #    name: Français
      #    nav_translations:
      #      Astronomie: Astronomie
      #      Elektrotechnik: Électrotechnique
      #      Informatik: Informatique
      #    site_name: l'outils epwg.de
        - build: true
          default: false
          locale: en
          name: English
          nav_translations:
            Astronomie: Astronomy
            Elektrotechnik: Electrical engineering
            Informatik: Informatics
          site_name: epwg.de tools
      reconfigure_material: false
      reconfigure_search: true

  - color-theme:
      theme_color: '#ff9933' #'#FF9933'
      secondary_color: 'complementary'

  - w3css-classes: {}

  - encryptcontent:
      title_prefix: ''
      summary: 'Verschlüsselte Testseite.'
      placeholder: '12345'
      password_button_text: 'ENTER'
      decryption_failure_message: 'Falsches Passwort, bitte "12345" eingeben.'
      encryption_info_message: 'Bitte "12345" eingeben.'
      input_class: 'w3-input'
      button_class: 'w3-button w3-theme-l1 w3-hover-theme'
      hljs: False
      arithmatex: False
      mermaid2: False
      #remember_password: true
      #session_storage: true
      encrypted_something:
        myNav: [div, id]
        myToc: [div, id]
        myTocButton: [div, id]
      search_index: 'dynamically' #dynamically
      password_button: True
      webcrypto: true
      selfhost: true
      selfhost_download: true
      selfhost_dir: 'files'
      reload_scripts:
        - '#theme'
      translations:
        en:
          title_prefix: ''
          summary: 'Encrypted Test Page.'
          placeholder: '12345'
          password_button_text: 'ENTER'
          decryption_failure_message: 'Wrong password, please enter "12345".'
          encryption_info_message: 'Please enter "12345".'

markdown_extensions:
    - attr_list
    - pymdownx.escapeall:
        hardbreak: true